name: Tests

on:
  push:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: |
          npx eslint ./src --ext .ts,.tsx --quiet
          npx stylelint "./src/**/*.scss"
          npx tsc --project tsconfig.json --noEmit
          npx prettier -c "./src/**/*.ts" "./src/**/*.tsx" "./src/**/*.scss"
